"""add role to user

Revision ID: 08ff414a8309
Revises: 5905790c351f
Create Date: 2026-08-18 12:26:20.182485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from database.models.User import UserRole

# revision identifiers, used by Alembic.
revision: str = '08ff414a8309'
down_revision: Union[str, Sequence[str], None] = '5905790c351f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_role = sa.Enum('ADMIN', 'USER', 'SUPERADMIN', name='user_role')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role.create(op.get_bind(), checkfirst=True)
    op.add_column('user', sa.Column('role', user_role, nullable=False, server_default='USER'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "role")

    user_role.drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
