"""add path to product image

Revision ID: fe556dfe1304
Revises: ca1ee478f65b
Create Date: 2026-08-29 12:35:46.078118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe556dfe1304'
down_revision: Union[str, Sequence[str], None] = 'ca1ee478f65b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_image', sa.Column('path', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_image', 'path')
    # ### end Alembic commands ###
